[package]
name = "agent-ebpf"
version = "0.1.0"
edition = "2021"

[dependencies]
agent-common = { path = "../agent-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "agent"
path = "src/main.rs"
